FROM tensorflow/tensorflow:2.18.0-gpu

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends ffmpeg libsm6 libxext6 wget git

# Install Python packages
COPY pyproject.toml .
ENV UV_LINK_MODE=copy
RUN pip install uv && uv sync --extra model

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
