[project]
name = "ds340-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.0.1",
    "ipykernel>=6.29.5",
    "numpy>=2.1.1",
    "pandas>=2.2.3",
    "polars>=1.7.1",
    "ruff>=0.6.5",
    "torch>=2.4.1",
    "torchaudio>=2.4.1",
    "torchvision>=0.19.1",
]

[tool.ruff]
include = ["pyproject.toml"]
